### ISSUE TITLE
Iterate over and fine tune model

### ISSUE THREAD

**Issue by barbarastrasser** [neurobagel/annotation-tool-ai#39]
# Outcome
The focus of this milestone is to iterate and fine-tune the model with available data in the form of already annotated datasets as well as semantic context input (ontologies, etc.). This is especially relevant to improve the retrieval of the `Diagnosis` and `Assessment Tool` entities.

# Resources:
- [Hard coded annotation categories](https://github.com/neurobagel/annotation_tool/blob/99f7400580f8f0866b948c03967869d25ade9e09/store/index.js#L31-L65)
- [Example files used for testing in annotation tool](https://github.com/neurobagel/annotation_tool/tree/main/cypress/fixtures/examples/good)
- [An organization containing annotated datasets](https://github.com/OpenNeuroDatasets-JSONLD)

# Tasks
Note: the code template for the  third and fourth task will get ready in  #45

- [x] ~~#45~~
- [x] #49
- [x] #50
- [x] ~~Create embeddings from already annotated data~~
- [x] #40
- [x] ~~Create embeddings from semantically meaningful data sources (ontology, documents, etc.)~~
- [x] ~~Choose and store embeddings in a vectorstore~~
- [x] ~~Reorganize LLM invocation - response of queries for document retrieval of vector stores should be included in the prompt handed over to the LLM~~
- [x] ~~Validate the annotated data~~
